server:  
  port: ${PING_SERVICE_PORT:3333}

eureka:  
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    metadata-map:
      instanceId: pong-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true