server:  
  port: ${PING_SERVICE_PORT:3333}

eureka:  
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true